include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_relative_lib_imports: true
    eol_at_end_of_file: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - lib/src/grpc/generated
    - external/
    - example/
    - tool/
